<script lang="ts">
  import "../../lib/components/Card3.svelte";
</script>

<ul>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
  <li>
    <custom-card>
      <img
        src="https://picsum.photos/200/300.jpg"
        alt="hello"
        width={300}
        height={200}
      />
    </custom-card>
  </li>
</ul>
